### ISSUE TITLE
useRxCollection returns null in "Simple Example" scenario

### ISSUE THREAD

**Issue by doronfeldman** [cvara/rxdb-hooks#11]
Hey, I'm trying to use rxdb-hooks,
I really like the idea.

Inside my component i'm using this as follows:

```
const db = useRxDB(); // Works as expected returning a DB that contains the collection named 'contacts'
const collection = useRxCollection<Contact>('contacts'); // returns null at first
const query = collection.find().where('phoneNumber').equals('5555555'); // we need the collection to create a query
const { result: contacts, isFetching } = useRxQuery<Contact>(query); // We need the query in order use this hook, cannot be conditional
```

Thank you.

**Comment by cvara** [comment]
Hey @doronfeldman. You can do:

```typescript
const collection = useRxCollection<Contact>('contacts'); // returns null at first

const query = useMemo(() => {
  if (!collection) {
    return null;
  }
  return collection.find().where('phoneNumber').equals('5555555');
}, [collection]); // 👈 any variable query arguments should be inserted here

// query may be null, but it's ok, useRxQuery will handle it
const { result: contacts, isFetching } = useRxQuery<Contact>(query);
```

Or you can directly use `useRxData` that internally does the same thing:

```typescript
const queryConstructor = useCallback((c: RxCollection) => 
  c.find().where('phoneNumber').equals('5555555'),
  [] // 👈 any variable query arguments should be inserted here
);

const { result: contacts, isFetching } = useRxData<Contact>('contacts', queryConstructor);
```

In any case you don't directly need to get the db instance via `useRxDB`.

**Comment by doronfeldman** [comment]
Hey @cvara 
thank you for the help!

Consider adding a sample project, it could simplify future integration

**Comment by Unforgiven-wanda** [comment]
Hello,
If I might hijack this issue instead of creating a new one (@cvara 's answer did help me btw). How would you go about to get the active pagination page?
To both add an `active` class to the correct pagination button and to add a `previous` and `next` buttons

**Comment by cvara** [comment]
@Unforgiven-wanda `currentPage` as well as the total `pageCount` are returned inside the result of useRxQuery and useRxData (which is a wrapper around useRxQuery) as seen [here](https://github.com/cvara/rxdb-hooks#result-rxqueryresultt). You can utilize them to render any sort of pagination button arrangement you see fit.
