### ISSUE TITLE
useRxData and component re-render

### ISSUE THREAD

**Issue by wnz99** [cvara/rxdb-hooks#16]
Hi,
I'm fetching paginate results in a component with the following code and using https://github.com/welldone-software/why-did-you-render to monitor re-renders:

```javascript
  const queryConstructor = (collection: any) => {
    return collection.find().sort({ created_at: 'desc' });
  };


  const {
    result: videos,
    isFetching,
    fetchMore,
    isExhausted,
    resetList,
    currentPage,
  } = useRxData<VideoDocType>('videos', queryConstructor, {
    pageSize: 5,
    pagination: 'Infinite',
  });
```

This is the only hook I've in the code.

I've noticed this warning:

![image](https://user-images.githubusercontent.com/12447140/97846434-e6c9b780-1ce5-11eb-9ac9-f67b67278fcd.png)

is this expected?

**Comment by cvara** [comment]
@wnz99 `useRxData` will re-subscribe to the query returned by the query constructor every time the query constructor function changes, which in your example happens on every render. Thus you should be memoizing your query constructor like so:
```typescript
import { useCallback } from 'react';

...

const queryConstructor = useCallback((collection: any) => {
  return collection.find().sort({ created_at: 'desc' });
}, []); // 👈 if your queries depend on component props add them here
```

**Comment by wnz99** [comment]
alright, thank you, I had missed that part of the docs.

**Comment by cvara** [comment]
No worries. Closing this then.

**Comment by wnz99** [comment]
Hi, I'm reopening because I followed your advice but it looks like the component is still re-rendering. That happens also if I move the query function outside of the component scope with something like:

```javascript
const queryConstructor = (collection: any) => {
  console.log('run queryConstructor');
  return collection.find().sort({ created_at: 'desc' });
};

const VideosList: React.FC<Props> = () => {

...

  const {
    result: videos,
    isFetching,
    fetchMore,
    isExhausted,
    resetList,
    currentPage,
  } = useRxData<VideoDocType>('videos', queryConstructor, {
    pageSize: 5,
    pagination: 'Infinite',
  });

...

return ...

}
```

Perhaps I'm doing something else wrong?

**Comment by cvara** [comment]
You are not doing anything wrong, the re-renders you are left with are perfectly normal.

The RxDB create API is asynchronous, which means that your provider most probably renders once _without_ a `db` and then a second time (once you have created an rxdb instance) _with_ a `db`. Those 2 renders yield the same result, since `useRxData` & `useRxQuery` initialize in a "loading" state (isFetching: true) while waiting to get their hands on a db they can query, and remain in this state once the do perform the query. This -most probably- is why wdyr complains.
