### ISSUE TITLE
useRxData doesn't support findByIds

### ISSUE THREAD

**Issue by nirvdrum** [cvara/rxdb-hooks#46]
I'm trying to query for a set of IDs with a query supplied to `useRxData`. Unfortunately, it doesn't seem to work. The type definitions don't appear to be compatible, as `findByIds` returns a `Map<string, doc_type>`. Thinking maybe the type definitions just needed to be updated, I typed the query constructor instance as `any`, but that didn't help. The query never resolves and `isFetching` is always `true`.

**Comment by cvara** [comment]
It seems that `findOne()` is the single exception among collection _query_ functions that exposes a promise-based API, so it can't be used with `useRxData` which naturally expects a query object with a [BehaviorSubject **$** attached to it](https://rxdb.info/rx-query.html#observe-).

I will try to work on a patch for this soon.

**Comment by cvara** [comment]
Fixed in [4.0.2](https://github.com/cvara/rxdb-hooks/releases/tag/4.0.2).
