### ISSUE TITLE
Is RXDB v12 supported?

### ISSUE THREAD

**Issue by Gugols** [cvara/rxdb-hooks#51]
Hi,
Been using with RXDB V11 & rxdb-hooks with no problems. However, noticed that a major RXDB version 12 has been released. Wondering, whether is supported by rxdb-hooks?

Based on README, it seems not yet?
![2022-06-08_13-48](https://user-images.githubusercontent.com/7780981/172598794-cf48d3ae-004f-498e-8d9b-80cf02426b06.png)

**Comment by cvara** [comment]
RxDB 12 support will be tracked by #52. Closing this.
