### ISSUE TITLE
rxdb 13 breaks lazy collection creation

### ISSUE THREAD

**Issue by cvara** [cvara/rxdb-hooks#61]
[Lazy collection creation](https://github.com/cvara/rxdb-hooks#lazy-instantiation-of-rxdatabase--rxcollections) is broken when rxdb 13 is used. This means that data from collections that have been created retroactively are not picked up.

**Comment by darkowic** [comment]
Confirm. I just started to play around with these hooks and nothing works :sweat: Direct db calls like:
```
await db.transactions.find().sort("createdAt").exec()
```
work fine.
