### ISSUE TITLE
useRxData doesn't return result and keeps fetching

### ISSUE THREAD

**Issue by voiddev90** [cvara/rxdb-hooks#71]
When using rxdb-hooks version `5.0.1` with rxdb `14.1.2` the `useRxData` hook doesn't return any result but stays **stuck** in the `isFetching: true` state.

Our implementation uses Dexie as a storage engine. We also have a separate build using SQLite, which does work. Which indicates the query we're using seems to work. Using `useCollection` and manually querying the collection also returns the correct results.

Working example with Dexie:
```ts
const collection = useRxCollection<Submission>("submissions");

  useEffect(() => {
    collection
      ?.find()
      .exec()
      .then((results) => console.log(results));
  }, [collection]);
```

This doesn't work with Dexie:
```ts
const { result, isFetching } = useRxData<Submission>("submissions", (collection) =>
    collection.find()
  );
```

Both examples work with SQLite.

Do you have any idea what could be causing this issue?

**Comment by cvara** [comment]
This may possibly relate to #65. Could you try using version [5.0.2](https://github.com/cvara/rxdb-hooks/releases/tag/5.0.2) of rxdb-hooks?

**Comment by voiddev90** [comment]
@cvara Version 5.0.2 seems to be working. Thanks!
